services:
  - type: web
    name: cricket-odds-api
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: RENDER
        value: true
      - key: DATA_DIR
        value: /var/data
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
