services:
  - type: web
    name: cricket-odds-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: RENDER
        value: true
      - key: DATA_DIR
        value: /app/data  # Changed to use app directory since free tier doesn't support persistent disks
    autoDeploy: true
